language: node_js
node_js:
  - 5.1.0
before_script:
  - tsc
notifications:
  webhooks:
    urls:
      - 'https://www.travisbuddy.com/'
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never
