@startuml
(*) --> first

note right: do not count a first character 

first --> [character] character
first --> [space] space
first --> [end] "end"
character --> [same character type] character
character --> [space, end] space
character -down-> [different character type] "count --"

if "" then
--> [count=0] (*)
else
-up-> [count > 0]character
end if

space -down-> [character] "count --"
space -> [space, end] space
space --> [blank] "blank count --"
if "" then
--> [count=0] (*)
else
-up-> [count > 0] space
end if

"end" --> [end] "count -- at blnkline"
note right: need count blank line
if "" then
--> [count=0] (*)
else
-up-> [count > 0] space
end if

"end" --> [character] "count --"
"end" --> [space] space
"count -- at blnkline" --> "end"

@enduml
