@startuml
(*) --> [count] first
note right: first character does not count
first --> [character] character
first --> [space] space
character --> [same type character] character
character --> [space] space
character -down-> [different type character] "count --"
space -down-> [character] "count --"
space -> [space] space
"count --" -up-> [if count > 0 ] character
"count --" --> [if count = 0 ] (*)
note left
TODO
* count end of line
* stop at blank line
* stop at end of document
end note
@enduml

