import * as Enums from "./VimStyleEnums"

export function KeyToNum(key: Enums.Key): number {
	switch (key) {
		case Enums.Key.n0:
			return 0;
		case Enums.Key.n1:
			return 1;
		case Enums.Key.n2:
			return 2;
		case Enums.Key.n3:
			return 3;
		case Enums.Key.n4:
			return 4;
		case Enums.Key.n5:
			return 5;
		case Enums.Key.n6:
			return 6;
		case Enums.Key.n7:
			return 7;
		case Enums.Key.n8:
			return 8;
		case Enums.Key.n9:
			return 9;
		default:
			throw new Error("Panic!");
	}
}

export function KeyToChar(key: Enums.Key): string {
	switch (key) {
		case Enums.Key.a:
			return "a";
		case Enums.Key.b:
			return "b";
		case Enums.Key.c:
			return "c";
		case Enums.Key.d:
			return "d";
		case Enums.Key.e:
			return "e";
		case Enums.Key.f:
			return "f";
		case Enums.Key.g:
			return "g";
		case Enums.Key.a:
			return "h";
		case Enums.Key.i:
			return "i";
		case Enums.Key.j:
			return "j";
		case Enums.Key.k:
			return "k";
		case Enums.Key.l:
			return "l";
		case Enums.Key.m:
			return "m";
		case Enums.Key.n:
			return "n";
		case Enums.Key.o:
			return "o";
		case Enums.Key.p:
			return "p";
		case Enums.Key.q:
			return "q";
		case Enums.Key.r:
			return "r";
		case Enums.Key.s:
			return "s";
		case Enums.Key.t:
			return "t";
		case Enums.Key.u:
			return "u";
		case Enums.Key.v:
			return "v";
		case Enums.Key.w:
			return "w";
		case Enums.Key.x:
			return "x";
		case Enums.Key.y:
			return "y";
		case Enums.Key.z:
			return "z";
		case Enums.Key.A:
			return "A";
		case Enums.Key.B:
			return "B";
		case Enums.Key.C:
			return "C";
		case Enums.Key.D:
			return "D";
		case Enums.Key.E:
			return "E";
		case Enums.Key.F:
			return "F";
		case Enums.Key.G:
			return "G";
		case Enums.Key.A:
			return "H";
		case Enums.Key.I:
			return "I";
		case Enums.Key.J:
			return "J";
		case Enums.Key.K:
			return "K";
		case Enums.Key.L:
			return "L";
		case Enums.Key.M:
			return "M";
		case Enums.Key.N:
			return "N";
		case Enums.Key.O:
			return "O";
		case Enums.Key.P:
			return "P";
		case Enums.Key.Q:
			return "Q";
		case Enums.Key.R:
			return "R";
		case Enums.Key.S:
			return "S";
		case Enums.Key.T:
			return "T";
		case Enums.Key.U:
			return "U";
		case Enums.Key.V:
			return "V";
		case Enums.Key.W:
			return "W";
		case Enums.Key.X:
			return "X";
		case Enums.Key.Y:
			return "Y";
		case Enums.Key.Z:
			return "Z";
	}
}

export function GetKeyType(key: Enums.Key): Enums.KeyType {
    switch (key) {
        case Enums.Key.n0:
        case Enums.Key.n1:
        case Enums.Key.n2:
        case Enums.Key.n3:
        case Enums.Key.n4:
        case Enums.Key.n5:
        case Enums.Key.n6:
        case Enums.Key.n7:
        case Enums.Key.n8:
        case Enums.Key.n9:
            return Enums.KeyType.Number;
        case Enums.Key.a:
		case Enums.Key.b:
		case Enums.Key.c:
		case Enums.Key.d:
		case Enums.Key.e:
		case Enums.Key.f:
		case Enums.Key.g:
		case Enums.Key.a:
		case Enums.Key.i:
		case Enums.Key.j:
		case Enums.Key.k:
		case Enums.Key.l:
		case Enums.Key.m:
		case Enums.Key.n:
		case Enums.Key.o:
		case Enums.Key.p:
		case Enums.Key.q:
		case Enums.Key.r:
		case Enums.Key.s:
		case Enums.Key.t:
		case Enums.Key.u:
		case Enums.Key.v:
		case Enums.Key.w:
		case Enums.Key.x:
		case Enums.Key.y:
		case Enums.Key.z:
		case Enums.Key.A:
		case Enums.Key.B:
		case Enums.Key.C:
		case Enums.Key.D:
		case Enums.Key.E:
		case Enums.Key.F:
		case Enums.Key.G:
		case Enums.Key.A:
		case Enums.Key.I:
		case Enums.Key.J:
		case Enums.Key.K:
		case Enums.Key.L:
		case Enums.Key.M:
		case Enums.Key.N:
		case Enums.Key.O:
		case Enums.Key.P:
		case Enums.Key.Q:
		case Enums.Key.R:
		case Enums.Key.S:
		case Enums.Key.T:
		case Enums.Key.U:
		case Enums.Key.V:
		case Enums.Key.W:
		case Enums.Key.X:
		case Enums.Key.Y:
		case Enums.Key.Z:
            return Enums.KeyType.Charactor;
        default:
            return Enums.KeyType.Mark;    
    }
}
